### ISSUE TITLE
Integrate scandit as Widget

### ISSUE THREAD

**Issue by fryette** [PalotaCompany/flutter_scandit#1]
Is it possible to integrate scandit as Widget?
I would like to draw over Scandit control+ and show content unders scanner

**Comment by KholofeloMoyaba** [comment]
@fryette currently this is not possible in the current state of the plugin. The current implementation has all the scanning work happening on the native side (Android and iOS) - what comes back to the dart/flutter side is the decoded barcode.

Having it as a widget will first require some investigation to see how it can be done. If it is done, it will be done as new functionality for people who want a more interactive mode.

I'm tagging this as a new feature.

**Comment by fryette** [comment]
@KholofeloMoyaba implemented by myself based on your plugin solution

**Comment by KholofeloMoyaba** [comment]
@fryette thank you for the feedback. On our side, we haven't had a chance to integrate it into the plugin. Will post once there is info about the feature.

I hope your implementation pans out well. Did you target both Android and iOS?

**Comment by fryette** [comment]
Right now only iOS, but this week Android version will be ready as well.
